#'
#' Data Snapshot for Two Numeric Variables
#'
#' @description
#' Function provides snapshot of the linear relationship between two numeric variables (scatterplot and adjusted r value), as well as some
#' summary statistics for the two numeric variables.
#'
#' @details
#' When given two numeric variables, x and y, this function produces summary statistics (max, min, median and mean) and a plot
#' that allows the user to get a quick snapshot of the data and in particular their linear relationship
#' (if any). Generally, the adjusted r squared value, a value between 0 and 1 (displayed as a percentage), represents the proportion of variance
#' observed for a dependent variable explained by the independent variable in a linear regression model.
#'
#' @param data needs to be a data frame (for e.g., a tibble)
#' @param x This input is a numeric variable from a tibble or dataframe, for e.g. column with numeric values
#' @param y This input is a numeric variable from a tibble or dataframe, for e.g. column with numeric values
#'
#' @return This function returns summary statistics tables for numeric variables, a scatterplot and adjusted R squared value
#'
#' @examples
#' data_snapshot(mtcars, hp, mpg)
#' data_snapshot(gapminder::gapminder, lifeExp, gdpPercap)
#'
#' @export
#'
#' @importFrom dplyr summarise
#' @importFrom ggplot2 ggplot aes geom_point labs theme_bw
#' @importFrom broom glance
#' @importFrom magrittr %>%
#'

# creating the function
data_snapshot <- function(data, x, y) {

# assigning x and y to specify the columns in the dataset for the function
# this ensures x is interpreted as df$x and not globalenv()$x, same goes for y

  x <- eval(substitute(x), data)
  y <- eval(substitute(y), data)

# the function will only accept both x and y as numeric variables, and if this
# is not the case, will return the error message below

  if(!(is.numeric(x) && is.numeric(y))){
    stop(" Both inputs need to be numeric variables. Please check. Column x is of class: ", class(x),
         " and Column y is of class: ", class(y))
  }

# generates a summary table (tibble) for x with 4 columns: max, min, mean, median
  summary_for_x <- data %>%
    dplyr::summarise(max = max(x, na.rm = TRUE),
              min = min(x, na.rm = TRUE),
              mean = mean(x, na.rm = TRUE),
              median = stats::median(x, na.rm = TRUE))

# generates a summary table (tibble) for y with 4 columns: max, min, mean, median
  summary_for_y <- data %>%
    dplyr::summarise(max = max(y, na.rm = TRUE),
              min = min(y, na.rm = TRUE),
              mean = mean(y, na.rm = TRUE),
              median = stats::median(y, na.rm = TRUE))
# produces scatter plot of y vs x
  quickplot_scatter <- ggplot2::ggplot(data, ggplot2::aes(x=x, y=y)) +
    ggplot2::geom_point() +
    ggplot2::labs( x = "Input X variable",
          y = "Input Y variable") +
    ggplot2::theme_bw()
# running linear model on data and extracting adjusted r squared value
  simple_linear_model <- stats::lm(y ~ x, data)
  summary_simplelm <- broom::glance(simple_linear_model)
# r_adj_value <- summary_simplelm$adj.r.squared
  r_adj_value <- paste("Adjusted R-square is", round(summary_simplelm$adj.r.squared*100,2),"%")
# assigning list of objects generated by function to a variable
  ret_list <- list(summary_for_x, summary_for_y, quickplot_scatter, r_adj_value)
# ensuring that the function returns a list stored in the object ret_list
  return(ret_list)
}
